4 3 create and update advert form
thinknetica-django-lab-04/charmheroku pull request #34
Opened 2021-08-08 13:47 UTC by charmheroku

Closes #23

2021-08-09 08:36 UTC, inkviz96 approved these changes

2021-08-09 08:36 UTC, inkviz96 commented on main/models.py
>          return self.username
в методе __str__ надо возвращать строку

2021-08-09 10:53 UTC, mikhailborodin requested changes

2021-08-09 10:53 UTC, mikhailborodin commented on main/views.py
> +        form.instance.category_id = 1
явные указатели – плохая практика

2021-08-09 17:33 UTC, charmheroku commented on main/views.py
> +        form.instance.category_id = 1
Вынес выбор категории в форму. Убрал плохую практику. Спасибо

2021-08-09 17:33 UTC, charmheroku commented on main/models.py
>          return self.username
Сделано. Спасибо

2021-08-10 22:12 UTC, inkviz96 approved these changes

2021-08-11 07:54 UTC, mikhailborodin approved these changes

2021-08-11 19:56 UTC, merged