feat: add signals from allauth and users to group
thinknetica-django-lab-04/charmheroku pull request #48
Opened 2021-08-13 20:50 UTC by charmheroku

Closes #40

2021-08-15 22:41 UTC, inkviz96 approved these changes

2021-08-16 06:38 UTC, mikhailborodin requested changes

2021-08-16 06:38 UTC, mikhailborodin commented on main/signals.py
> +    group = Group.objects.get(name="common_users")
если такой группы нет, то будет ошибка

2021-08-16 07:50 UTC, charmheroku commented on main/signals.py
> +    group = Group.objects.get(name="common_users")
Спасибо. Добавил исключение.

2021-08-16 09:23 UTC, mikhailborodin approved these changes

2021-08-16 10:30 UTC, merged